### ISSUE TITLE
Cannot install in v11

### ISSUE THREAD

**Issue by DnD-World** [sw5e-foundry/mandalorian-codex#1]
I get this when I try to install
![Screenshot_66](https://github.com/sw5e-foundry/mandalorian-codex/assets/137470054/f8d7d093-7a03-4732-ba5f-1f1550f644df)

**Comment by unrealkakeman89** [comment]
My apologies, that was pointing to the old location. The new manifest link should be:

https://github.com/sw5e-foundry/mandalorian-codex/releases/latest/download/module.json

**Comment by DnD-World** [comment]
hmmm, I get the same message, new url, same message...
